x-redis-cluster-common: &redis_cluster_common
  image: redis:8.4.0-bookworm
  command: &redis_cluster_command
    - "redis-server"
    - "--save"
    - ""
    - "--appendonly"
    - "no"
    - "--protected-mode"
    - "no"
    - "--cluster-enabled"
    - "yes"
    - "--cluster-config-file"
    - "nodes.conf"
    - "--cluster-node-timeout"
    - "5000"
  restart: unless-stopped
  networks:
    - redis-network

services:
  redis-cluster-master-1:
    <<: *redis_cluster_common
    container_name: redis-cluster-master-1
    ports:
      - "17020:6379"

  redis-cluster-master-2:
    <<: *redis_cluster_common
    container_name: redis-cluster-master-2
    ports:
      - "17021:6379"

  redis-cluster-master-3:
    <<: *redis_cluster_common
    container_name: redis-cluster-master-3
    ports:
      - "17022:6379"

  redis-cluster-replica-1:
    <<: *redis_cluster_common
    container_name: redis-cluster-replica-1
    ports:
      - "17023:6379"

  redis-cluster-replica-2:
    <<: *redis_cluster_common
    container_name: redis-cluster-replica-2
    ports:
      - "17024:6379"

  redis-cluster-replica-3:
    <<: *redis_cluster_common
    container_name: redis-cluster-replica-3
    ports:
      - "17025:6379"

  redis-cluster-init:
    image: redis:8.4.0-bookworm
    container_name: redis-cluster-init
    depends_on:
      - redis-cluster-master-1
      - redis-cluster-master-2
      - redis-cluster-master-3
      - redis-cluster-replica-1
      - redis-cluster-replica-2
      - redis-cluster-replica-3
    command:
      - "sh"
      - "-c"
      - |
        until redis-cli -h redis-cluster-master-1 ping; do sleep 1; done
        until redis-cli -h redis-cluster-master-2 ping; do sleep 1; done
        until redis-cli -h redis-cluster-master-3 ping; do sleep 1; done
        until redis-cli -h redis-cluster-replica-1 ping; do sleep 1; done
        until redis-cli -h redis-cluster-replica-2 ping; do sleep 1; done
        until redis-cli -h redis-cluster-replica-3 ping; do sleep 1; done
        redis-cli --cluster create \
          redis-cluster-master-1:6379 \
          redis-cluster-master-2:6379 \
          redis-cluster-master-3:6379 \
          redis-cluster-replica-1:6379 \
          redis-cluster-replica-2:6379 \
          redis-cluster-replica-3:6379 \
          --cluster-replicas 1 --cluster-yes
    restart: "no"
    networks:
      - redis-network

networks:
  redis-network:
    name: redis-network
